/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#1b1c1c",
        "on-secondary-fixed-variant": "#5a4300",
        "surface-container-high": "#eae7e7",
        "primary": "#9e4200",
        "background": "#fcf9f8",
        "tertiary-fixed": "#f3dfca",
        "tertiary-fixed-dim": "#d6c4af",
        "inverse-on-surface": "#f3f0f0",
        "secondary-container": "#fed577",
        "on-background": "#1b1c1c",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#793100",
        "surface-container-low": "#f6f3f2",
        "on-secondary-container": "#785b02",
        "on-surface-variant": "#574239",
        "on-tertiary-fixed-variant": "#514535",
        "on-secondary-fixed": "#251a00",
        "on-primary-fixed": "#341100",
        "on-primary-container": "#5b2300",
        "inverse-surface": "#303030",
        "primary-fixed-dim": "#ffb691",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-tint": "#9e4200",
        "on-tertiary-fixed": "#231a0d",
        "tertiary": "#6a5c4c",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-highest": "#e4e2e1",
        "inverse-primary": "#ffb691",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#ab9a87",
        "surface": "#fcf9f8",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#3e3224",
        "primary-fixed": "#ffdbcb",
        "outline-variant": "#dec1b3",
        "outline": "#8a7267",
        "primary-container": "#f27c38",
        "surface-variant": "#e4e2e1",
        "secondary-fixed-dim": "#e9c266",
        "on-error": "#ffffff",
        "secondary-fixed": "#ffdf9a",
        "on-tertiary": "#ffffff",
        "surface-container": "#f0eded",
        "secondary": "#775a01",
        brand: {
          orange: '#F27C38',
          gold: '#C9A44C',
          sand: '#EAD7C2',
          charcoal: '#2B2B2B',
          background: '#f8f2eb',
        },
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}